name: Pull Request Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Lint HTML and CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install htmlhint stylelint

      - name: Lint HTML files
        run: npx htmlhint "**/*.html"
      
      - name: Lint CSS files
        run: npx stylelint "**/*.css"

  build:
    name: Build Static Website
    runs-on: ubuntu-latest
    needs: linting

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Parcel
        run: npm install -g parcel-bundler

      - name: Build website
        run: parcel build src/index.html --dist-dir dist
